version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - ISSUE_BODY=Sample issue
    command: python -m ai_buddy.orchestrator
