name: CI
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install mypy bandit pip-audit
      - name: Tests
        run: pytest backend --cov=backend
      - name: Type check
        run: mypy --strict backend
      - name: Bandit
        run: bandit -r backend -q
      - name: Pip audit
        run: pip-audit -r backend/requirements.txt
      - name: Upload coverage
        uses: codecov/codecov-action@v3
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps
        run: |
          cd frontend && npm ci
      - name: Test
        run: |
          cd frontend && npm run test
  docker:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          docker build -f Dockerfile.backend -t backend:test .
          docker build -f Dockerfile.frontend -t frontend:test .
      - name: Scan backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend:test
      - name: Scan frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend:test
  nightly-security:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install pip-audit
          pip-audit -r backend/requirements.txt -f json > audit.json || true
          high=$(jq '[.[] | select(.cvss > 9)] | length' audit.json)
          echo "high=$high" >> $GITHUB_OUTPUT
        id: audit
      - if: steps.audit.outputs.high != '0'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: security/high
          content-filepath: audit.json
