name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install backend deps
        run: python -m pip install --quiet -r backend/requirements.txt
      - name: Install frontend deps
        run: npm --prefix frontend ci
      - name: Lint backend
        run: |
          black --check backend
          isort --check-only backend
      - name: Type check
        run: mypy backend
      - name: Security scan
        run: bandit -r backend -q
      - name: Test backend
        run: pytest -q backend
      - name: Lint frontend
        run: npm --prefix frontend run lint
      - name: Test frontend
        run: npm --prefix frontend test -- --watch=false
